### ISSUE TITLE
some question about model and the result

### ISSUE THREAD

**Issue by 2snoopy88** [ML4ITS/mtad-gat-pytorch#10]
Hi Axel,
I have some question  for  the repo
1. i read the OmniAnomaly code, i found it use 25/55 as the out_dim  for the MSL and SMAP,  i also open the MSL data, only the   first dimension has value, so can i think the MSL and SMAP  is just univariate time series, but almost paper say the dataset  is multivariate, it's  make me confuse.
2. i use the repo as the baseline for my research, i found you replace the decoder from VAE to GRU, so did you try the original VAE for the decoder , i do some experiment  but i can't  achieve  the result  in the original  paper,  so if you try VAE can  achieve  the result in original  paper

I will appreciate it if you can reply as soon as possible.

**Comment by axeloh** [comment]
Hello! 

1. MSL and SMAP has one so-called telemetry value, and then the rest are one-hot encoded values. I don't know if OmniAnomaly tries to forecast/reconstruct the one-hot encoded values, but to us that makes little sense. Therefore, we use all features as input (making it a multivariate), but only forecast/reconstruct the telemetry value. 
2. Yes, we talk about this in #2.

**Comment by khadijakhaldi** [comment]
Hi @axeloh, if I have 4 columns, each column represent sensor data, and anomaly is based on the 4 features. Can I reconstruct all the 4 columns with your model ? 
If yes, can you please show me what I need to  modify ?
