### ISSUE TITLE
Some question about the param target_dims

### ISSUE THREAD

**Issue by ShaoSK** [ML4ITS/mtad-gat-pytorch#11]
I have the question about this param, as the mtad-gat is a multivariable time series model which uses modules to catch the time dependencyand the feature dependency, if use only one dim to training and testing, it just degenerates into univariate time series model. What's the use of the corresponding module of feature dependency in this situation?

**Comment by axeloh** [comment]
Hello, 

MTAD-GAT is indeed a model made for multivariate time-series. If the input is univariate, then the feature-oriented GAT module will have no effect. However, the time-oriented GAT module will still serve the purpose of attending to different time-steps. 

Recall that even though datasets SMAP and MSL have univariate output, the input is still multivariate, and so both GAT modules will be utilized.

**Comment by JacobTheEngineer86** [comment]
I'm a bit confused on this. You said that the input of the MSL dataset is multivariate, but when I analyze the npy files going into the network, the only relevant data exists along a single dimension, which suggests to me the incoming data is univariate. Am I wrong in thinking that?
