### ISSUE TITLE
Exception: Dataset ".\DATASETS\DATA\SMAP_TRAIN_MD.CSV" not available.

### ISSUE THREAD

**Issue by dheiver** [ML4ITS/mtad-gat-pytorch#16]
raise Exception(f'Dataset "{dataset}" not available.')
Exception: Dataset ".\DATASETS\DATA\SMAP_TRAIN_MD.CSV" not avaipython.exe .\train.py --dataset .\datasets\data\smap_train_md.csvv) PS C:\Users\dheiver\Desktop\Nova pasta\mtad-gat-pytorch>
{'dataset': '.\\DATASETS\\DATA\\SMAP_TRAIN_MD.CSV', 'group': '1-1', 'lookback': 100, 'normalize': True, 'spec_res': False, 'kernel_size': 7, 'use_gatv2': True, 'feat_gat_embed_dim': None, 'time_gat_embed_dim': None, 'gru_n_layers': 1, 'gru_hid_dim': 
150, 'fc_n_layers': 3, 'fc_hid_dim': 150, 'recon_n_layers': 1, 'recon_hid_dim': 150, 'alpha': 0.2, 'epochs': 30, 'val_split': 0.1, 'bs': 256, 'init_lr': 0.001, 'shuffle_dataset': True, 'dropout': 0.3, 'use_cuda': True, 'print_every': 1, 'log_tensorboard': True, 'scale_scores': False, 'use_mov_av': False, 'gamma': 1, 'level': None, 'q': None, 'dynamic_pot': False, 'comment': ''}
Traceback (most recent call last):
  File "C:\Users\dheiver\Desktop\Nova pasta\mtad-gat-pytorch\train.py", line 43, in <module>
    raise Exception(f'Dataset "{dataset}" not available.')
Exception: Dataset ".\DATASETS\DATA\SMAP_TRAIN_MD.CSV" not available.
(env) PS C:\Users\dheiver\Desktop\Nova pasta\mtad-gat-pytorch>

**Comment by KANGWOOLEE1234** [comment]
I'm in the same situation.
Is there any good way to solve this problem?

**Comment by zmusaddique** [comment]
> I'm in the same situation. Is there any good way to solve this problem? ![image](https://user-images.githubusercontent.com/83321216/182983287-b791a9f4-1031-4de1-a548-3c8de0564022.png)

You need to download the dataset specified by the README.md file. Make sure you have navigated to the correct directory
