### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ServerMachineDataset/processed\\machine-1-1_train.pkl'

### ISSUE THREAD

**Issue by xiaokai01** [ML4ITS/mtad-gat-pytorch#22]
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ServerMachineDataset/processed\\machine-1-1_train.pkl'

**Comment by mmmagic1** [comment]
需要先运行preprocess.py
