### ISSUE TITLE
My understanding of mtad _ gat.py does not reflect the ' Multivariate Time-series ' in the title of the paper. 

### ISSUE THREAD

**Issue by yuanyuanyuantang** [ML4ITS/mtad-gat-pytorch#31]
The data x received by the forward ( ) function in  mtad _ gat.py  is in the shape of ( batch number, window, fearture number ), but on the feature number, only the data of the first column is not 0, and the data of the remaining columns are all 0. Isn 't that splicing all the dimensions of data into a long one-dimensional data ? 
![image](https://github.com/ML4ITS/mtad-gat-pytorch/assets/101562821/104eea0f-943f-4245-a1c0-65bc4615ce95)

**Comment by khadijakhaldi** [comment]
I believe that is one hot encoding of categorical features, thats why you see 0's

**Comment by yuanyuanyuantang** [comment]
thank you
